name: cantwait28
description: A Flutter project that counts days down to exciting dates in the future.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.1

  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  firebase_ui_auth: ^1.12.0
  intl: ^0.18.1
  firebase_auth: ^4.16.0
  bloc: ^8.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
